### ISSUE TITLE
Error: Could not create backend

### ISSUE THREAD

**Issue by giyaseddin** [huggingface/text-embeddings-inference#137]
### System Info

Unable to run the container that runs a local model.

```bash
text-embeddings-1  | Error: Could not create backend
text-embeddings-1  | 
text-embeddings-1  | Caused by:
text-embeddings-1  |     Could not start backend: Runtime compute cap 52 is not compatible with compile time compute cap 75
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Step 1:
create a `docker-compose.yml` file:

```yaml
version: '3.8'

services:
  text-embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:0.6
    ports:
      - 80:80
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
    volumes:
      - ../../models:/models
      - ../../model_cache:/model_cache
    command:
      - "--model-id"
      - /models/my-local-model
      - "--huggingface-hub-cache"
      - /model_cache/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
```

using a gpu `Quadro M4000 (8 GB GPU memory)` (GPT+) 

Then `sudo docker compose up` will lead to the following output:

```bash
Attaching to text-embeddings-1
text-embeddings-1  | 2024-01-24T12:26:54.934592Z  INFO text_embeddings_router: router/src/main.rs:112: Args { model_id: "/mod***/*****-**del", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, hf_api_token: None, hostname: "f6d9edfd6987", port: 80, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: Some("/model_cache/"), json_output: false, otlp_endpoint: None }
text-embeddings-1  | 2024-01-24T12:26:54.952359Z  INFO text_embeddings_core::tokenization: core/src/tokenization.rs:22: Starting 8 tokenization workers
text-embeddings-1  | 2024-01-24T12:26:55.034236Z  INFO text_embeddings_router: router/src/lib.rs:239: Starting model backend
text-embeddings-1  | Error: Could not create backend
text-embeddings-1  | 
text-embeddings-1  | Caused by:
text-embeddings-1  |     Could not start backend: Runtime compute cap 52 is not compatible with compile time compute cap 80
text-embeddings-1 exited with code 1
```

### Expected behavior

It runs on my RTX 3050 Ti laptop GPU with no issues
